name = "Mimi"
uuid = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
version = "1.5.4-DEV"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Classes = "1a9c1350-211b-5766-99cd-4544d885a0d1"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
StringBuilders = "db12335b-fddc-5e1b-b0ee-42071d21ae50"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GlobalSensitivityAnalysis = "1b10255b-6da3-57ce-9089-d24e8517b87e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
FilePaths = "8fc22ac5-c921-52a6-82fd-178b2807b824"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ExcelReaders = "c04bee98-12a5-510c-87df-2a230cb6e075"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ExcelFiles = "89b67f3b-d1aa-5f6f-9ca4-282e8d98620d"

[compat]
Statistics = "1"
Distributions = "0.21, 0.22, 0.23, 0.24, 0.25"
CSVFiles = "0.16, 1.0"
VegaLite = "1, 2, 3"
TableTraits = "0.4.1, 1"
Classes = "1.2"
IterTools = "1.3"
DelimitedFiles = "1"
NamedArrays = "0.9, 0.10"
IteratorInterfaceExtensions = "0.1.1, 1"
JSON = "0.21"
StatsBase = "0.32, 0.33, 0.34"
DataStructures = "0.17, 0.18"
StringBuilders = "0.2"
ProgressMeter = "1.9"
MacroTools = "0.5"
FileIO = "1"
julia = "1.6"
GlobalSensitivityAnalysis = "1.0"
DataFrames = "0.19.1, 0.20, 0.21, 0.22, 1.0"
Electron = "3.1, 4, 5"
FilePaths = "0.8"

[targets]
test = ["TestItemRunner", "Pkg", "Statistics", "NamedArrays", "ExcelFiles", "ExcelReaders", "DelimitedFiles", "Documenter", "Random", "Test", "ZipFile", "MacroTools", "Query"]
